apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-outside-ingress-only-{{ include "service.name" . }}
spec:
  podSelector: 
    matchLabels:
      component: {{ include "service.name" . }}
  ingress:
  - {}